model: 
  row_anchors : [121, 131, 141, 150, 160, 170, 180, 189, 199, 209, 219, 228, 238, 248, 258, 267, 277, 287]
  griding_num : 200
  num_lanes : 4
  num_layers : 1
  hidden_sizes : [512]
  kernel_sizes : [3]  
  backbone : "18"  
  size : [288, 800] # [288, 800]
  seq_len : 3
  cls_dim : [201, 18, 4]
  bias : True
  device : 0

train : 
  dataset : "gazebo_dataset"
  batch_size : 24
  path : "C:\\Users\\pales\\Desktop\\gazebo_dataset"  
  optimizer : "Adam"
  epoch : 200  
  current_epoch : 0
  train_list_path : "/homes/apalese/CULane/list/train_gt.txt"
  sim_loss_w : 0.0
  shp_loss_w : 0.0
  scheduler : ""  # ["multi", "cos"]
  steps : [25,38]
  gamma : 0.1
  warmup : "linear"
  warmup_iters : 695  
  weight_decay : 0.0001
  learning_rate : null
  momentum : 0.9
  weights : null # the weight for the griding cells and the weight for the no-line cell

test: 
  test_list_path : "C:\\Users\\pales\\Desktop\\gazebo_dataset\\list\\test.txt"
  test_work_dir : "demo_work_dir"
  test_batch_size : 1

validate: 
  val_list_path: "/homes/apalese/CULane/list/val_gt.txt"
  test_list_path : "/homes/apalese/CULane/list/val.txt"
  validate_work_dir : ""

save:
  weights_path : "state_dicts\\ep333_best.pth"
  overwrite : False
  keep_weights : "" # dir
  resume_epoch : 0
  note : ""
  best_sum_val_loss : 1000000
  best_score : 0
